### ISSUE TITLE
Save button?

### ISSUE THREAD

**Issue by angaertner** [nicebread/RESQUE#13]
Is there some sort of save button available, or can we give the information somewhere that the entries are saved automatically? After filling in the blanks I worried that something might get lost during the process...

**Comment by alpkaanaksu** [comment]
@angaertner Everything is saved automatically. For dropdown, radio and checkbox items, any change triggers that; for text input, clicking away from the textbox does it. (with some special cases, for example if an indicator is used in a condition of another indicator, the saved information gets updated after each key stroke.)

I'll add this information to the website.

**Comment by alpkaanaksu** [comment]
Is showing a modal with more information about the website at the beginning (for example when a user visits the website for the first time, or if there are no saved results) a good idea?

![IMG_F1CBF4427086-1](https://github.com/nicebread/RESQUE/assets/68744864/39c9d510-fcb5-4464-85b1-7e51d03ad73a)

**Comment by nicebread** [comment]
Yes, I like the "welcome modal". Additionally, there should be a link on the website (which opens another modal, the "privacy modal"), which contains all information on privacy:

- no server communication, all data is stored only locally
- How is it stored locally? (Cookies / html5 technology?)
- How can locally stored data be deleted? Can this be done via a button on the website?
- What to do, if you use a public machine to fill in the website? Then it is stored there, and you probably want to delete it.

**Comment by nicebread** [comment]
In Google Drive, there is a small modal info banner on the top that shows "Saving changes ... done" whenever something is changed in the document. I remember that many people were confused with Google docs (before that banner) because they were searching for a "Save" button.

Can you implement such a small "Saving changes ... done" (where the "done" is shown 500ms after the first part) at each change? Just to calm the users.

**Comment by alpkaanaksu** [comment]
<img width="649" alt="Screenshot 2023-09-04 at 20 34 51" src="https://github.com/nicebread/RESQUE/assets/68744864/29617ed1-5d8c-4a2b-98b1-daa90f8f3883">
<img width="647" alt="Screenshot 2023-09-04 at 20 42 12" src="https://github.com/nicebread/RESQUE/assets/68744864/e3cf03a6-ea7c-4b2b-86c8-9e03f17d1a69">

**Comment by nicebread** [comment]
Nice!

**Comment by alpkaanaksu** [comment]
I created an info modal (which is also shown as a welcome modal if there is no old data in the browser). f89569a2d0783fc28c65c086eeafb105d80efd05

<img width="823" alt="Screenshot 2023-09-19 at 00 22 59" src="https://github.com/nicebread/RESQUE/assets/68744864/be47d58f-eac0-47aa-a493-94e74858df46">

@nicebread It would be nice if we had a general explanation of the idea (+ why someone would need this tool?), I put '...' as a placeholder. I could also write something but I think it is better if you do it.

**Comment by nicebread** [comment]
Looks great! I added some information text in https://github.com/nicebread/RESQUE/commit/47911bad23839600422142ad155b35fc4efe6604
