### ISSUE TITLE
Add flag for "Top paper"

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#15]
Applicants should select their 3 best papers (out of the, say, 10 provided papers).
Please implement a checkbox labelled "This is one of my three best papers", with a logic that maximally 3 can be selected.
(Maybe an alert if a 4th paper is selected: "You already selected three best papers. Please deselect one of them to select a new one.")

**Comment by alpkaanaksu** [comment]
I created a checkbox that updates a global list:
![Screenshot 2023-08-31 at 17 48 18](https://github.com/nicebread/RESQUE/assets/68744864/73ed1666-eaab-44d2-9f02-436c112e4ccb)

Selected top papers are also shown in the metadata tab, you can click on the 'papers' to switch to the corresponding tab:
![Screenshot 2023-08-31 at 17 49 42](https://github.com/nicebread/RESQUE/assets/68744864/c6f1ec4e-ea90-4838-a516-f879b8766f44)

You get a warning if you try to select more than 3 papers:
![Screenshot 2023-08-31 at 17 53 48](https://github.com/nicebread/RESQUE/assets/68744864/718ddd19-755e-4b5d-b009-7a6fea7dcc91)

**Comment by nicebread** [comment]
Nice!

**Comment by nicebread** [comment]
But seems to have a bug: I only selected 1 top paper, but the Meta-Tab shows both existing papers and the meta-tab itself:
<img width="653" alt="image" src="https://github.com/nicebread/RESQUE/assets/2391270/59fb667b-1e25-4858-bbf9-387b9b9fa60c">

**Comment by alpkaanaksu** [comment]
That happens, when a paper which is marked as a top paper has no DOI. (everything without a DOI is shown) We don't have another unique identifier for papers. Yesterday I thought that it is safe to assume that all papers have a DOI and there is no way to fix the bug. But thinking about it now, it could actually be fixed by using the position in the result list as the unique identifier. I will try that.

**Comment by alpkaanaksu** [comment]
Fixed fb7f59e4c1337f39c6dcfd9dc545e365f148d570

I tested it by importing your No Score Paper and creating 3 other no name papers, seems to be working correctly now:

<img width="1027" alt="Screenshot 2023-09-01 at 10 05 55" src="https://github.com/nicebread/RESQUE/assets/68744864/14bfdbcc-ad8f-4540-a6aa-8592c46b6ade">

**Comment by nicebread** [comment]
Thanks! What happens when somebody deletes a publication (which is AFAIK not possible yet - but should be possible - and then the relative position changes?
(in nearly all cases a doi should be present, but I can imagine edge cases where no doi is present. So it should work without doi)

**Comment by alpkaanaksu** [comment]
We don't have hardcoded positions anywhere, so top papers display would still work because they are rendered dynamically after each change. I tested these assumptions by manually removing a paper in the console:

```js
results.splice(index, 1);
save();
location.reload();
```

**Comment by nicebread** [comment]
OK, I think we can close it then.
