### ISSUE TITLE
Publication short name in tab pill

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#20]
- Remove field "publication number" (we don't need it)
- Number publications consecutively/automatically ("Pub 1", "Pub 2", "Software 1", "Dataset 1")
- Add text field "Short name for publication" with maximum 12 characters. This is only used for displaying the tab pill in the top row (i.e., if I enter "PSE" as short name, show "Pub 1 (PSE)". This way, it is easier to find publications in the tab row when you have many of them.

**Comment by alpkaanaksu** [comment]
Or maybe just take the first 4 words?

'The long long title of a publication' -> 'The long long title...'

**Comment by alpkaanaksu** [comment]
Another idea would be going back to the sidebar we had initially. We would have those on both sides, like Twitter:

<img width="1470" alt="Screenshot 2023-08-29 at 10 58 30" src="https://github.com/nicebread/RESQUE/assets/68744864/c77c9c03-1436-4a86-8a51-dfe0f44b656b">

**Comment by nicebread** [comment]
Yes, let's used the sidebar to the left. When you enter 12 publications, the vertical row gets quite long and confusing.
And yes to "Use first 4 words of title". Then we probably need no custom short name.

**Comment by alpkaanaksu** [comment]
> When you enter 12 publications, the vertical row gets quite long and confusing.

Yes, I hate it.

**Comment by alpkaanaksu** [comment]
I changed the layout.

<img width="1470" alt="Screenshot 2023-08-29 at 12 56 36" src="https://github.com/nicebread/RESQUE/assets/68744864/e9e75c47-55ab-4ab1-b860-f29df35cdbfb">
