### ISSUE TITLE
Scoring bug with "own data"

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#23]
If you add stuff under "Own data collection", you earn points.
If you then switch to "No data", the fields are hidden, but you still get the points nested under "own data collection".

(How to deal with this generally? At the one hand, I like that the information stays in the hidden fields (it would be bad to re-enter everything, just because you clicked on another option on a filter item. But the points should not be given/ shown).

**Comment by alpkaanaksu** [comment]
Updating the conditions should be enough to fix this:

```json
"points": [
    { "value": 1, "condition": "$P12 =|= [0, 1] && $P11 === 3" }
]
```
