### ISSUE TITLE
Split "Own data or data reuse (check all that apply)"?

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#25]
The "Own data or data reuse (check all that apply)" indicator is a bit strange:

Actually it is a forced choice/mandatory indicator, as at least one option must be clicked - either "no data", or one or more of the first 3 options. At the moment, it is possible to select nothing.

How can we solve that?

Idea:
Split into more questions:

Q1a: Does this paper use any kind of data in a substantive way (new data, reuse of existing data, or simulated data?) --> Yes / No
Q1b (if yes in Q1a): What kind of data do you use?  (check all that apply)
  ☐ Own new data collection
  ☐ Reuse of own existing data set
  ☐ Reuse of someone else's existing data set
  ☐ Simulated data
   --> here, a validation would be that at least one of the checkboxes needs to be selected.

+ "info": "Data set acquisition often is a collaborative enterprise with different contributor roles. Select 'Reuse of **own** existing data set' only, if you would qualify as a co-author with substantive contributions in a stand-alone data set publication of that data set."

Q1c (see email from Anne): Type of data (check all that apply):
   ☐ Questionnaire
   ☐Behavioral
   ☐Physiological / Biological
   ☐ Other:  (+textfield)

**Comment by alpkaanaksu** [comment]
<img width="645" alt="Screenshot 2023-09-04 at 16 36 21" src="https://github.com/nicebread/RESQUE/assets/68744864/6f01fc9c-364c-424c-a504-89bc89649e2a">
<img width="1093" alt="Screenshot 2023-09-04 at 16 37 11" src="https://github.com/nicebread/RESQUE/assets/68744864/75a775b3-a47c-4f72-a73a-7225c248fcb9">

**Comment by alpkaanaksu** [comment]
I implemented the 'min_selected' functionality 3fe83e471d4e01e77c669b803a489bebc941284c

<img width="398" alt="Screenshot 2023-09-19 at 21 11 45" src="https://github.com/nicebread/RESQUE/assets/68744864/17529358-799f-44b3-ada4-d84e7f17c57f">
