### ISSUE TITLE
Get rid of all scores / one point is left over?

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#27]
If I select "not applicable" where ever possible, still 1 point is left. I don't know where this comes from?

See attached file (rename to .json, as a json upload is not possible here).

[resque_1693372668078.txt](https://github.com/nicebread/RESQUE/files/12471933/resque_1693372668078.txt)

**Comment by nicebread** [comment]
Fixed in 81fbce7b27608a0d06c3278d26870d90222f0c65.

When scores are down to 0, the score box says "No score - applicant requests manual processing", even if P8 has not been checked. But if _everything_ is "not applicable", this boils down to manual processing. Hence, the message seems appropriate.

**Comment by alpkaanaksu** [comment]
'No score' is shown if max score is 0.
