### ISSUE TITLE
Add meta-data: First change, last change; name of rater

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#29]
Please add datetime of: "created" and "last change" to the results json. (Maybe more metadata will come later).
For transparency reasons, display all metadata that is saved in the json also on the "Author" tab.

Rename author tab to "Author / Metadata", and add a field "Name of external rater (optional)".

**Comment by alpkaanaksu** [comment]
<img width="1470" alt="Screenshot 2023-08-31 at 11 58 20" src="https://github.com/nicebread/RESQUE/assets/68744864/669aa132-81bd-4058-bbb6-089974a94106">

**Comment by alpkaanaksu** [comment]
Now we can insert variable values into info items. I also implemented *typed-insertions*:

date_created = 1693475745498

`$date_created` -> "1693475745498"

`$date_created@datetime` -> "31/08/2023, 11:55:45"

`$date_created@date` -> "31/08/2023"

We can implement other types if needed in the future.
