### ISSUE TITLE
Warning box if max score too low

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#34]
When you always tick "not applicable", you can bring the max points down to very few points (down to zero). It is easy to achieve a 100% score with a single applicable point.

--> Add a warning to the score info box, if the max score falls below 5 points. 
Give score box a light orange background, add warning: "Note: Many indicators are not applicable. Manual processing of this publication is recommended".

**Comment by alpkaanaksu** [comment]
Implemented here: 676549da4c42f5eb089c055b7a2d8c8a192d8a30

<img width="435" alt="Screenshot 2023-09-18 at 18 02 13" src="https://github.com/nicebread/RESQUE/assets/68744864/f098057c-0233-457f-a146-ea20a48fc731">

**Comment by nicebread** [comment]
Nice!
