### ISSUE TITLE
webfrom complains about title format for software

### ISSUE THREAD

**Issue by aaronpeikert** [nicebread/RESQUE#36]
![image](https://github.com/nicebread/RESQUE/assets/29424409/f1f53f79-4d58-4eb2-adc2-3ff8c674bde0)

**Comment by nicebread** [comment]
Ah, software is not implemented at all yet ;-)
Try out "New publication", this is more mature.

**Comment by alpkaanaksu** [comment]
And we still don't have real input validation (also for publications)
