### ISSUE TITLE
Show warning for "clear" button

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#39]
The button is dangerous: A single click can destroy all of your data if you did not export it.

Please add a warning:
"Warning: This will delete all of your local data. Do you want to export the data to a file?"

--> two buttons in modal:

- "Cancel"
- "Export data to local file"
- "Clear all data" (<- in red)

**Comment by alpkaanaksu** [comment]
Implemented here 56bd40d79d00faa4e654cec97538d5ce0943bbcc

<img width="471" alt="Screenshot 2023-09-19 at 18 37 10" src="https://github.com/nicebread/RESQUE/assets/68744864/441a8285-96a9-45a7-a014-92f8165d7738">
