### ISSUE TITLE
Make right pane scrollable

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#40]
With large info boxes (and smaller screens), the content of the right pane exceeds the available space:

<img width="481" alt="image" src="https://github.com/nicebread/RESQUE/assets/2391270/1d474b4c-8f16-4965-be61-b2e25454ca79">

Can you make the right pane scrollable?

**Comment by alpkaanaksu** [comment]
Fixed here: 4024d900ebfe4d957d19b7cad4b6ed95ccfdbc95

Making the whole thing scrollable was not good idea (I tried it and did not like it), ideally users can always see their score and the links at the bottom.

The info box grows as needed until the dynamic max size is reached, then it becomes scrollable.

<img width="444" alt="Screenshot 2023-09-19 at 11 54 12" src="https://github.com/nicebread/RESQUE/assets/68744864/927a2783-b85f-4dd3-993c-caa6b84174b3">

<img width="445" alt="Screenshot 2023-09-19 at 11 54 33" src="https://github.com/nicebread/RESQUE/assets/68744864/7caa0f48-b43e-4610-b118-3cb3d82ebeb1">

**Comment by nicebread** [comment]
I like your implementation
