### ISSUE TITLE
Overall score infobox

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#47]
Dann bräuchten wir noch ein Infofenster, was den **Durchschnitt** der Scores (über alle eingetragenen Papers, Data sets, Software) anzeigt. 

In dem Fenster wäre dann eine Warnung, wenn weniger als z.B. 5 Research Output eingetragen sind:
„⚠️ Please provide at least 5 research contributions that can be scored (e.g. by adding more empirical papers, data sets, or software contributions)"

See also #48

**Comment by alpkaanaksu** [comment]
I changed the score box. (ebae5e1966ca14b0d07d90b30d570d7ec7a51da6)

`minROWarningThreshold` can be provided in menu.js or as a query parameter (https://nicebread.github.io/RESQUE/web/index.html?minROWarningThreshold=3).

<img width="432" alt="Screenshot 2023-10-10 at 16 05 30" src="https://github.com/nicebread/RESQUE/assets/68744864/6f301a8d-87ef-4cc1-bffc-f314af909364">

<img width="435" alt="Screenshot 2023-10-10 at 16 02 08" src="https://github.com/nicebread/RESQUE/assets/68744864/584c0f73-4297-4f3e-9a62-4cf46b738d2a">

<img width="433" alt="Screenshot 2023-10-10 at 16 17 39" src="https://github.com/nicebread/RESQUE/assets/68744864/6f4d7981-469b-42ef-81bf-03955596b799">

<img width="436" alt="Screenshot 2023-10-10 at 16 20 55" src="https://github.com/nicebread/RESQUE/assets/68744864/70198fb5-ecd8-4326-9ee8-2117e97c4d42">

**Comment by nicebread** [comment]
Nice! Can you add "Overall Score (mean) **across XX scored research outputs**" (scored := P_suitable == Yes)

**Comment by alpkaanaksu** [comment]
We don't have enough space for that kind of long text. Maybe something like this?

<img width="433" alt="Screenshot 2023-10-15 at 12 44 08" src="https://github.com/nicebread/RESQUE/assets/68744864/1b8b14e1-1bba-4b10-a98e-bc211819583e">

I am not sure.

**Comment by nicebread** [comment]
Yes, I like this solution

**Comment by alpkaanaksu** [comment]
I pushed my changes 5d6f4fda6f708e9cf31cda42b69a52fe27066709
