### ISSUE TITLE
Add RESQUE-Builder (global variables in GET request)

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#50]
Most committees won't be able/willing to customize their web form by changing the JSON files.
Can we provide a low-barrier customization solution for them?

## Idea:
The global variables in menu.js can be set/overwritten with GET variables, e.g.: 
`https://nicebread.github.io/RESQUE/web?maxTopPapers=3&affiliation=LMU+München+Sozialpsychologie&max=8`

And we could provide a simple "RESQUE Builder"; a website where committees can point and click their customization in a simple web form, which then provides the customized link. This could be further submitted to a link shortener, and then they can provide that link in their job announcement. Can we also encode a short instruction for the participants ("Most servers and clients have a limit of 8192 bytes (8 KB)").

That also means, that the global variables should be stored in the exported json file.

What do you think?

**Comment by alpkaanaksu** [comment]
I think this would work and it is one of the easier ways to solve this problem.

Including a short instruction might work (https://stackoverflow.com/a/417184), the URL will be very ugly at the end, but we could at least try.

We should also think about saving to file / loading: saved values are not valid if the configuration is not the same.

We can maybe use a URL shortener API and provide shorter URLs in the RESQUE-Builder?

**Comment by alpkaanaksu** [comment]
@nicebread What about variables that are specific to research output types? For example 'minIndicatorsWarningThreshold' is defined per type.

**Comment by alpkaanaksu** [comment]
c0fcaef38d760ba475fc69ad5d47c889709c4b24 I implemented a better config system, which takes 1) global config, 2) params specific to type, 3) query config into account.

Query params can override everything.

https://nicebread.github.io/RESQUE/web/?max=2

<img width="376" alt="Screenshot 2023-10-09 at 13 30 16" src="https://github.com/nicebread/RESQUE/assets/68744864/fb28535f-6cd0-4b96-ac34-a813e64be964">

**Comment by nicebread** [comment]
Nice!
(I just had a boundary case: my local storage had 5 publications, and now the form says "5 of 2 slots used, you can't add more publications." - which is OK).
A potential problem could be: Applicants use the generic web form (and enter data, e.g. for their CV), and then they click on the customized link of the hiring committee, which loads their data, but is to some extent incompatible).
Could we have some warning "You have old data present. Do you want to load it, or start with a fresh form?"
(I think we have such a thing when the *version* is incompatible. Maybe there is an easy way to check whether the meta-parameters of the form have changed?)

**Comment by alpkaanaksu** [comment]
This is why I didn't close the issue. We have to save the config together with the results and compare the values with the current environment. I just included the query params while working on #48.

**Comment by alpkaanaksu** [comment]
I am playing with some ideas and created a simple page: https://nicebread.github.io/RESQUE/web/builder (82cac86cf23781d15c9429afd5a0000280fe0763)

Only the global config options are working, values are only reflected in the generated link if they differ from our defaults.

What do you think? I don't know what the builder looked like in your imagination.

**Comment by nicebread** [comment]
Exactly like this! Simply a lean website, no schnickschnack.

**Comment by alpkaanaksu** [comment]
> @nicebread What about variables that are specific to research output types? For example 'minIndicatorsWarningThreshold' is defined per type.

Something like this could work: `?pubs:minIndicatorsWarningThreshold=3`

**Comment by nicebread** [comment]
Yes!

**Comment by alpkaanaksu** [comment]
Now it is possible to:
- provide configuration parameters for specific types (7a3845b124d6315ca7521b1006755f9ec3d0090c)
  - like `?pub:minIndicatorsWarningThreshold=3`
- change type specific parameters in RESQUE Builder (8af3b17d7530b3c8e83f7b6b402cd1aa9c7e82d4)
- show a warning if the saved configuration and the current configuration are different (0f9ecb542f914e9222e9488d640e4eede7bc2818)
  - hash the query config objects to compare them
  - overwrite saved config if the user decides to use old data
  - show clear modal if they wish to start fresh
  - avoid making this a breaking change: if no queryConfig field is present in the data, create one with the current configuration parameters

I think we have all needed basic functionality for this feature?

(It looks a bit ugly when you open the clear modal on top of the warning modal, I'll change that but is not a part of the core functionality.)

<img width="515" alt="Screenshot 2023-10-27 at 13 09 54" src="https://github.com/nicebread/RESQUE/assets/68744864/6f630ca7-933b-4a4b-866c-b2d2952bad96">

**Comment by nicebread** [comment]
Excellent - good job!
