### ISSUE TITLE
Add new foldable section in right sidebar: "Tips for external raters"

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#57]
Along with "info" and "background": new section "Tips for external raters", which is initially folded.
(Authors rating their own papers don't need that information, so it should not be take visual space unless you unfold it).

Add new object to json: `"tip_external"`

**Comment by alpkaanaksu** [comment]
Done: 31416b8133c86321677b40d5dee26bb82e53c86f

<img width="431" alt="Screenshot 2023-11-18 at 21 52 17" src="https://github.com/nicebread/RESQUE/assets/68744864/d9d4581b-c1c8-415a-b0be-5181b64ec7fa">
<img width="430" alt="Screenshot 2023-11-18 at 21 52 24" src="https://github.com/nicebread/RESQUE/assets/68744864/115cba72-469d-4508-ac92-bd2d55c04d10">
