### ISSUE TITLE
Score.R: Return scores for each indicator

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#58]
Can you update score.R, so that the scores for each indicator are returned?
With the indicator name as variable name (e.g., `P_ReproducibleScripts_FAIR`).

I need to aggregate specific indicators to create sub-scores (e.g., all indicators related to open data).

**Comment by nicebread** [comment]
Exzellent!

**Comment by nicebread** [comment]
Can you also add the maximum possible score for each indicator in the output?

**Comment by nicebread** [comment]
Should be fine, too. In the end, I need to compute relative scores from subsets of indicators.

E.g., for OpenData:

```
r$> scores_data                                                                                                                                                                                                                      
P_Data_Open_AccessLevel        P_Data_Open_FAIR P_Data_Open_AccessLevel        P_Data_Open_FAIR P_Data_Open_AccessLevel        P_Data_Open_FAIR P_Data_Open_AccessLevel        P_Data_Open_FAIR P_Data_Open_AccessLevel 
                   1.00                    0.75                    1.00                    0.00                    1.00                    0.00                    0.00                    0.00                    1.00 
       P_Data_Open_FAIR 
                   0.25 
```

Then I need to know how much candidates *could* have achieved with these indicators.

**Comment by alpkaanaksu** [comment]
Ok, writing a separate function would not work because some indicators could be not applicable. We are actually not duplicating the information by including it in the scoring result.

**Comment by alpkaanaksu** [comment]
We actually skip not-applicable indicators, do we need them in the output?

I added the indicator max scores to the scoring output:

<img width="396" alt="Screenshot 2023-11-21 at 20 54 28" src="https://github.com/nicebread/RESQUE/assets/68744864/54862e37-5ab1-4fbe-931b-5c6402b2b1ba">

**Comment by nicebread** [comment]
Works great now! 

> We actually skip not-applicable indicators, do we need them in the output?

Currently, I think: No.
