### ISSUE TITLE
Allow conditions across different core-X.jsons

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#63]
In core-pubs.json, I want to condition on a value from core-meta.json:

`"condition": "$P_Suitable === 'Yes' && $P_ReproducibleScripts =|= ['YesParts', 'YesEntire' && $RaterType === 'Applicant']"`

The last past, ` && $RaterType === 'Applicant'` does not work yet.
(I want to hide indicators that cannot be rated by external raters).

**Comment by alpkaanaksu** [comment]
We could create a new prefix, e.g. `meta$ExternalRater`, we already have the `global` prefix.

**Comment by alpkaanaksu** [comment]
Done in fd8c54546168b796fd108ef82affb75463922081.

`"condition": "$P_Suitable === 'Yes' && $P_ReproducibleScripts =|= ['YesParts', 'YesEntire'] && meta$RaterType === 'Applicant'` should work now.
