### ISSUE TITLE
mode=print: Meta-data on top of page

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#77]
In `mode=print`: Please add header with the following meta-data:

`<h1>RESQUE: Full list of indicators for type "Publication"</h1>`
`Version <pack version>, last update on <date of last change>`
(type is automatically extracted from the pack that is displayed)

--> need to add a field `Date` to the pack meta-data:

```
{
    "version": "0.2",
    "date": "2024-02-02",
    "prefix": "P",
    "title": "Publication",
```

Or should/can we retrieve the date of last change automatically from the git history?

**Comment by alpkaanaksu** [comment]
We still have the possibility to mix and match items from different packs (e.g. for cases, where we are specifically interested in clinical psych publications, which could come with extra items, so we mix 'P' (pubs) and 'CP' (clinical psych) packs).

This is what we see:
**RESQUE: Full list of indicators for type "Publication"**
Version P: 0.3.1; last update on P: 07/03/2024

In a case, where we mix P and CP, we could see something like:

Version P: 0.3.1, CP: 0.1.0; last update on P: 07/03/2024, CP: 01/01/2024

---

@nicebread I added your last commit dates as 'date' to the JSON files.
