### ISSUE TITLE
Add JSON field for "background"

### ISSUE THREAD

**Issue by nicebread** [nicebread/RESQUE#8]
We might need **three** fields with information for each indicator:

- "tooltip": A short mouse-over hover tooltip (targeted at users who fill in the form)
- "info": A longer text with extended information, how to fill in the form (displayed at the right side of the screen; targeted at users who fill in the form)
- "background": Background information and justification for the indicator; maybe with literature references. Not necessary for end-users who fill in the form; but relevant for administrators, or end-users who want to know more about an indicator. Display in the right column; make it collapsed by default (should not distract and only be shown upon request)

The latter might often be empty.

**Comment by alpkaanaksu** [comment]
## Initial state
<img width="425" alt="Screenshot 2023-08-09 at 23 59 08" src="https://github.com/nicebread/RESQUE/assets/68744864/be49cc14-4825-4307-b2a8-4edf7cde1e3d">

## Item with no info
<img width="431" alt="Screenshot 2023-08-09 at 23 59 26" src="https://github.com/nicebread/RESQUE/assets/68744864/158915fe-0780-4a71-bad2-86542a603249">

## Item with info
<img width="432" alt="Screenshot 2023-08-09 at 23 59 40" src="https://github.com/nicebread/RESQUE/assets/68744864/0526ab3d-850d-449f-b8d5-d6bd71a9a325">

## Item with info, background information expanded
<img width="430" alt="Screenshot 2023-08-10 at 00 00 01" src="https://github.com/nicebread/RESQUE/assets/68744864/1d95f90d-e96e-4675-99b0-54bd5777c83c">
