### ISSUE TITLE
Add info text to each indicator

### ISSUE THREAD

**Issue by alpkaanaksu** [nicebread/RESQUE#9]
JSON definitions (see `packs/`) now have the 'tooltip', 'info' and 'background' fields.

**Comment by alpkaanaksu** [comment]
Also add 'eval_dimension' to indicators where it is applicable/relevant.

**Comment by nicebread** [comment]
I wonder whether we really need the three levels "tooltip", "info", and "background".

Maybe merge "tooltip" and "info" and display the text both as tooltip and in the inbox on the right?

**Comment by alpkaanaksu** [comment]
I think having all three is useful.

Let's take 'Year of publication' as an example:
Tooltip: 'e.g. 2023'
Info: _a longer explanation_ (ok, it is pretty self eplanatory for this one)
Backgorund: _why we need this information_

We should aim to keep the tooltip text much shorter.

**Comment by nicebread** [comment]
OK, let's keep the three!

**Comment by alpkaanaksu** [comment]
@nicebread I don't know if users are going to click on 'CRediT roles' and see the role descriptions you added. We can keep the text there but having the same text for each role indicator might be a good idea, we can also highlight the selected role.

e.g. Conceptualization

---

Ideas; formulation or evolution of overarching research goals and aims.

- *lead:* You were the single leader for this specific activity. If you are the only person in a specific role, choose 'lead'.
- *equal:* You contributed equally to this activity, together with one or more other contributors (you should only choose this option if no other co-author would choose the 'lead' option).
- *supporting:* You had a supporting role, not leading.
- *no role:* You did not contribute to that activity.

---

**Comment by nicebread** [comment]
Yes, good idea!

**Comment by nicebread** [comment]
Shall we add a little (i) or (?) icon at each indicator (or at each SC option that has an info text attached)?
If users click on that, the text in the right sidebar gets highlighted (not only when a user selects the option).
